### ISSUE TITLE
data preprocessing is has a bug

### ISSUE THREAD

**Issue by khorshidisamira** [s-omranpour/Fake-News-Detection-Pytorch#4]
Hello,
I am trying to run your code but I get this error:
`
```
TypeError                                 Traceback (most recent call last)
Input In [44], in <cell line: 4>()
      2 os.makedirs(save_path, exist_ok=True)
      4 for eid in tqdm(events):
----> 5     xc, xs, y = get_event_features(eid)
      6     pickle.dump(
      7         {'x_capture': xc, 'x_score':xs, 'label': y}, 
      8         open(save_path + eid + '.pkl', 'wb')
      9     )

Input In [42], in get_event_features(eid)
     49         print(eid)
     50         print(doc)    
---> 51         X_text += [doc_vectorizer.infer_vector(
     52 #             jieba.lcut(doc)
     53             doc
     54         ).reshape(1,-1)]
     55     X_text = np.concatenate(X_text, axis=0)
     57     # stack all

File ~/Research_direction/Fake news mitigation multimodal/venv38/lib/python3.8/site-packages/gensim/models/doc2vec.py:620, in Doc2Vec.infer_vector(self, doc_words, alpha, min_alpha, epochs)
    592 """Infer a vector for given post-bulk training document.
    593 
    594 Notes
   (...)
    617 
    618 """
    619 if isinstance(doc_words, str):  # a common mistake; fail with a nicer error
--> 620     raise TypeError("Parameter doc_words of infer_vector() must be a list of strings (not a single string).")
    622 alpha = alpha or self.alpha
    623 min_alpha = min_alpha or self.min_alpha

TypeError: Parameter doc_words of infer_vector() must be a list of strings (not a single string).
```
`
What should I do?
Thanks!

**Comment by s-omranpour** [comment]
Hi,
Thank you for using my work and sharing the problem. The `infer_vector` method accepts a list of strings as the sequence of document words. The commented `jiebe.lcut` method is used to split Chinese words and returns a list of strings. When working with non-Chinese text, you can replace it with something like `doc.split()` to have a list of document words and pass it to the `infer_vecotor` function.

Let me know if there was any further issues.

Best,

**Comment by khorshidisamira** [comment]
Thank you for letting me know, I am trying to apply the code to Twitter data. 
I also appreciate it if you can share your requirements, e.g., python version, PyTorch, etc. Right now I have this error: 


 ```
 File "/tmp/ipykernel_2468582/2857088609.py", line 62, in experiment
  File "/home/user/Fake news mitigation/venv37/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 821, in validate
    return self._call_and_handle_interrupt(self._validate_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/home/user/Fake news mitigation/venv37/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/user/Fake news mitigation/venv37/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in _validate_impl
    results = self._run(model, ckpt_path=self.validated_ckpt_path)
  File "/home/user/Fake news mitigation/venv37/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1128, in _run
    verify_loop_configurations(self)
  File "/home/user/Fake news mitigation/venv37/lib/python3.7/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 40, in verify_loop_configurations
    __verify_eval_loop_configuration(trainer, model, "val")
  File "/home/user/Fake news mitigation/venv37/lib/python3.7/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 170, in __verify_eval_loop_configuration
    has_step = is_overridden(step_name, model)
  File "/home/user/Fake news mitigation/venv37/lib/python3.7/site-packages/pytorch_lightning/utilities/model_helpers.py", line 47, in is_overridden
    raise ValueError("Expected a parent")
ValueError: Expected a parent
```

I have found this https://stackoverflow.com/questions/69526806/pytorch-model-heplers-py-in-is-overridden-raise-valueerror-expected-a-paren but in your code I see `class CSIModel(pl.LightningModule)` so it should be fine but it's not!

**Comment by s-omranpour** [comment]
Hi,

I will answer this on the other issue you've opened, and I'm closing this one.

Best,
