### ISSUE TITLE
Training is not working, the packages are not compatible

### ISSUE THREAD

**Issue by khorshidisamira** [s-omranpour/Fake-News-Detection-Pytorch#5]
Hello,
I decided to open a new issue since it's a different bug and error. While running the training code, I get the following error, would you please upload a requirement.txt for python packages that you have used? e.g., python version, PyTorch version, etc. 

```
File "/tmp/ipykernel_2468582/2857088609.py", line 62, in experiment
 File "/home/user/Fake news mitigation/venv37/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 821, in validate
   return self._call_and_handle_interrupt(self._validate_impl, model, dataloaders, ckpt_path, verbose, datamodule)
 File "/home/user/Fake news mitigation/venv37/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
   return trainer_fn(*args, **kwargs)
 File "/home/user/Fake news mitigation/venv37/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in _validate_impl
   results = self._run(model, ckpt_path=self.validated_ckpt_path)
 File "/home/user/Fake news mitigation/venv37/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1128, in _run
   verify_loop_configurations(self)
 File "/home/user/Fake news mitigation/venv37/lib/python3.7/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 40, in verify_loop_configurations
   __verify_eval_loop_configuration(trainer, model, "val")
 File "/home/user/Fake news mitigation/venv37/lib/python3.7/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 170, in __verify_eval_loop_configuration
   has_step = is_overridden(step_name, model)
 File "/home/user/Fake news mitigation/venv37/lib/python3.7/site-packages/pytorch_lightning/utilities/model_helpers.py", line 47, in is_overridden
   raise ValueError("Expected a parent")
ValueError: Expected a parent
```

I have found this https://stackoverflow.com/questions/69526806/pytorch-model-heplers-py-in-is-overridden-raise-valueerror-expected-a-paren but in your code, I see `class CSIModel(pl.LightningModule)`, so it should be fine but it's not!

**Comment by s-omranpour** [comment]
Hi,

I will upload a `requirement.txt` file as soon as I could access the machine I've used to do the experiments. In the meantime, here's the versions that I remember for now:

python version: 3.8.10
pytorch version: 1.9.0
pytorch_lightning: 1.5.5

**Comment by khorshidisamira** [comment]
Thank you for the information. Now, this is what I get:
```
Failure # 1 (occurred at 2022-03-27_18-19-04)
Traceback (most recent call last):
  File "/home/usr/venv38n/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 886, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/usr/venv38n/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 675, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/usr/venv38n/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/usr/venv38n/lib/python3.8/site-packages/ray/worker.py", line 1763, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): [36mray::ImplicitFunc.train()[39m (pid=245834, ip=134.68.51.32, repr=experiment)
  File "/home/usr/venv38n/lib/python3.8/site-packages/ray/tune/trainable.py", line 319, in train
    result = self.step()
  File "/home/usr/venv38n/lib/python3.8/site-packages/ray/tune/function_runner.py", line 381, in step
    self._report_thread_runner_error(block=True)
  File "/home/usr/venv38n/lib/python3.8/site-packages/ray/tune/function_runner.py", line 531, in _report_thread_runner_error
    raise TuneError(
ray.tune.error.TuneError: Trial raised an exception. Traceback:
[36mray::ImplicitFunc.train()[39m (pid=245834, ip=134.68.51.32, repr=experiment)
  File "/home/usr/venv38n/lib/python3.8/site-packages/ray/tune/function_runner.py", line 262, in run
    self._entrypoint()
  File "/home/usr/venv38n/lib/python3.8/site-packages/ray/tune/function_runner.py", line 330, in entrypoint
    return self._trainable_func(self.config, self._status_reporter,
  File "/home/usr/venv38n/lib/python3.8/site-packages/ray/tune/function_runner.py", line 600, in _trainable_func
    output = fn()
  File "/tmp/ipykernel_245477/2857088609.py", line 61, in experiment
  File "/home/usr/venv38n/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in fit
    self._call_and_handle_interrupt(
  File "/home/usr/venv38n/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/usr/venv38n/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 772, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/usr/venv38n/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1198, in _run
    self._post_dispatch()
  File "/home/usr/venv38n/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1267, in _post_dispatch
    self.signal_connector.teardown()
  File "/home/usr/venv38n/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/signal_connector.py", line 99, in teardown
    signal.signal(signum, handler)
  File "/usr/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```
I'm not familiar with Ray, I found a solution that suggested having `os.environ["SLURM_JOB_NAME"] = "bash"` but it didn't help!

**Comment by khorshidisamira** [comment]
> 

I've fixed the thread error but still get
 ```
raise ValueError("Expected a parent")
ValueError: Expected a parent
``` 
error! 
In data, I've changed 
`class CSIDataset(Dataset):` 
to
 `class CSIDataset(pl.LightningDataModule):`  but no success :(

**Comment by khorshidisamira** [comment]
> Hi,
> 
> I will upload a `requirement.txt` file as soon as I could access the machine I've used to do the experiments. In the meantime, here's the versions that I remember for now:
> 
> python version: 3.8.10 pytorch version: 1.9.0 pytorch_lightning: 1.5.5

I tried to run the code with python version: 3.8.10 pytorch version: 1.9.0 pytorch_lightning: 1.5.5, but still getting the same error!

**Comment by s-omranpour** [comment]
Hi, 
That's a weird error. Although it's ok to use the `pl.LightningDataModule` there's no need for that and the vanilla PyTorch Dataset module should work fine itself. Is the line `super().__init__()` present in your code?

**Comment by khorshidisamira** [comment]
> 

Yes, I have the line `super().__init__()` present in the code. Would you please upload the requirements?
I am not sure what should I do.

**Comment by s-omranpour** [comment]
I added the `requirement.txt` file to the root directory. Please pull the master branch again and check if it fixes the problem.

**Comment by khorshidisamira** [comment]
> I added the `requirement.txt` file to the root directory. Please pull the master branch again and check if it fixes the problem.

This is what I get:
```
 python -V
Python 3.8.10
pip install -r requirement.txt 
Collecting absl-py==1.0.0
  Using cached absl_py-1.0.0-py3-none-any.whl (126 kB)
Collecting aiohttp==3.8.1
  Using cached aiohttp-3.8.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.3 MB)
Collecting aiosignal==1.2.0
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting argon2-cffi==21.3.0
  Using cached argon2_cffi-21.3.0-py3-none-any.whl (14 kB)
Collecting argon2-cffi-bindings==21.2.0
  Using cached argon2_cffi_bindings-21.2.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (86 kB)
Collecting async-generator==1.10
  Using cached async_generator-1.10-py3-none-any.whl (18 kB)
Collecting async-timeout==4.0.2
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting asynctest==0.13.0
  Using cached asynctest-0.13.0-py3-none-any.whl (26 kB)
Collecting attrs==21.4.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting backcall==0.2.0
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting bleach==4.1.0
  Using cached bleach-4.1.0-py2.py3-none-any.whl (157 kB)
Collecting cachetools==4.2.4
  Using cached cachetools-4.2.4-py3-none-any.whl (10 kB)
Collecting certifi==2021.10.8
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting cffi==1.15.0
  Using cached cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (446 kB)
ERROR: Could not find a version that satisfies the requirement charset-normalizer==2.0.12 (from -r requirement.txt (line 15)) (from versions: 0.1a0, 0.1.1a0, 0.1.2b0, 0.1.4b0, 0.1.5b0, 0.1.7, 0.1.8, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.4.0, 1.4.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9)
ERROR: No matching distribution found for charset-normalizer==2.0.12 (from -r requirement.txt (line 15))

```

**Comment by khorshidisamira** [comment]
By removing that requirement, I get this error too:
```
ERROR: Could not find a version that satisfies the requirement torch==1.9.0+cu102 (from -r requirement.txt (line 96)) (from versions: 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for torch==1.9.0+cu102 (from -r requirement.txt (line 96))
```

**Comment by khorshidisamira** [comment]
> I added the `requirement.txt` file to the root directory. Please pull the master branch again and check if it fixes the problem.

After solving the errors, I get the same error!
First, 
```
File "/usr/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
``` 
Which I have fixed it by adding 
```
def patch_signal_connector(trainer: Trainer):
        """
        Avoid using `signal` in `trainer.SignalConnector` if Lightning
        is not running in the main thread.
        """
        if threading.current_thread() is threading.main_thread():
            return

        warnings.warn(f"Lightning is not running in the main thread. "
                      f"Patching `trainer.SignalConnector` to avoid using `signal`.")

        def _no_signal_teardown(self):
            self._original_handlers = {}

        trainer.signal_connector._is_on_windows = lambda *_: True
        trainer.signal_connector.teardown = partial(_no_signal_teardown, trainer.signal_connector)

patch_signal_connector(trainer)

```
    
Next, 

```
raise ValueError("Expected a parent")
ValueError: Expected a parent
```

**Comment by khorshidisamira** [comment]
> I added the `requirement.txt` file to the root directory. Please pull the master branch again and check if it fixes the problem.

After debugging the code, I have found that `res = trainer.validate(val_loader)[0]` is causing 
```

raise ValueError("Expected a parent")
ValueError: Expected a parent
```
Any idea why?

**Comment by Luo-Yangyang** [comment]
> > I added the `requirement.txt` file to the root directory. Please pull the master branch again and check if it fixes the problem.
> 
> After debugging the code, I have found that `res = trainer.validate(val_loader)[0]` is causing
> 
> ```
> 
> raise ValueError("Expected a parent")
> ValueError: Expected a parent
> ```
> 
> Any idea why?

Could you give me your Datasets? Thanks~   my email: 492999561@qq.com
